spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hexagonal-example
    driver-class-name: org.postgresql.Driver
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect